### ISSUE TITLE
statismo fails to build with hdf5 1.10.1

### ISSUE THREAD

**Issue by iMichka** [statismo/statismo#258]
Hi. I am one of the homebrew-science maintainers. We just updated to the newest version of hdf5.

The build fails with:
```
/tmp/statismo-20170512-80760-m6iqk6/statismo-0.11.0/modules/core/src/ModelInfo.cxx
In file included from /tmp/statismo-20170512-80760-m6iqk6/statismo-0.11.0/modules/core/include/HDF5Utils.h:270:0,
                 from /tmp/statismo-20170512-80760-m6iqk6/statismo-0.11.0/modules/core/include/DataItem.h:42,
                 from /tmp/statismo-20170512-80760-m6iqk6/statismo-0.11.0/modules/core/include/DataManager.h:45,
                 from /tmp/statismo-20170512-80760-m6iqk6/statismo-0.11.0/modules/core/src/ModelInfo.cxx:41:
/tmp/statismo-20170512-80760-m6iqk6/statismo-0.11.0/modules/core/include/HDF5Utils.hxx: In static member function 'static void statismo::HDF5Utils::readMatrixOfType(const H5::CommonFG&, const char*, typename statismo::GenericEigenType<T>::MatrixType&) [with T = unsigned int; typename statismo::GenericEigenType<T>::MatrixType = Eigen::Matrix<unsigned int, -1, -1, 1, -1, -1>]':
/tmp/statismo-20170512-80760-m6iqk6/statismo-0.11.0/modules/core/include/HDF5Utils.hxx:119:25: error: 'const class H5::CommonFG' has no member named 'openDataSet'
     H5::DataSet ds = fg.openDataSet( name );
                         ^
```

Looking at the documentation, openDataSet is no more there:
https://support.hdfgroup.org/HDF5/doc/cpplus_RM/class_h5_1_1_common_f_g.html

Could you have a look a this? We are currently stuck with the update for statismo. Thanks in advance.
For ref.: https://github.com/Homebrew/homebrew-science/pull/5672

**Comment by ohirose** [comment]
Hi, I am a statismo user and also experienced a similar event. Fortunately, I succeeded to build statismo with hdf5-1.10.1 under macOS Sierra (version 10.12.4). However, after issuing the command ``./statismo-build-shape-model -h``, statismo printed the error message: ``dyld: Library not loaded: /usr/local/opt/hdf5/lib/libhdf5_cpp.100.dylib``. Thanks in advance.

**Comment by iMichka** [comment]
@ohirose Not sure how you succeed to build this. It seems it picked up an old hdf5 you have lying around. This is probably a different problem. If this is a homebrew problem please post there, so that there is no mixup in the issues :)

**Comment by marcelluethi** [comment]
@iMichka Thank you for reporting this and, of course, all your work with homebrew. 

The problem by itself seems to be reasonably easy to fix. It is a breaking change in the HDF5 interface. But since statismo depends on other libraries (such as VTK and ITK) which itself depend on particular version of HDF5, I expect the change to be quite messy. 

Unfortunately I do not have any time to have a good look at it during the next few weeks. How urgent would a fix be from your side? If it is pressing and nobody else has time to look into it,  the best solution might be to (temporarily) remove it from homebrew.

**Comment by iMichka** [comment]
@marcelluethi Just to be clear, VTK and ITK already build with the newest hdf5 :)

**Comment by iMichka** [comment]
@marcelluethi Did you have time to look at this?

**Comment by marcelluethi** [comment]
@iMichka Unfortunately I did not find the time to look at it yet. It also does not seem that I have much more free time in the near future. Unless somebody steps in, I think it is best to remove it from homebrew. In this way I will not be blocking you guys.

The reason for the lack of resources that go into statismo from the side of the original developers is, that we have currently no projects that make use of statismo.
