### ISSUE TITLE
Boost thread fails to compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by marcelluethi** [statismo/statismo#95]
Boost thread compilation fails on Ubuntu 14.04 (g++ 4.8.2) with the following error message:
./boost/atomic/atomic.hpp:202:16: error: ‘uintptr_t’ was not declared in this scope
 typedef atomic<uintptr_t> atomic_uintptr_t;

Using boost 1.56 solves the problem.
